//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Component()
        {
            this.Fault_Log = new HashSet<Fault_Log>();
        }
    
        public string SerialID { get; set; }
        public string Name { get; set; }
        public string Supplier { get; set; }
        public string Equipment { get; set; }
        public string Description { get; set; }
        public string Purchase_Cost { get; set; }
        public string Purchase_Date { get; set; }
        public string Expected_Lifetime { get; set; }
        public bool Kept_in_Stock { get; set; }
    
        public virtual Equipment Equipment1 { get; set; }
        public virtual Supplier Supplier1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fault_Log> Fault_Log { get; set; }
    }
}
