//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Login
    {
        public int LogID { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime Login_Timestamp { get; set; }
        public Nullable<System.DateTime> Logout_Timestamp { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
