//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Syslog
    {
        public long RefID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string Edited_Table { get; set; }
        public string Edited_PK { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
